fp16: False
wd_on_bias: True
accumulation: 1
use_zero: True

optimizer:
  name: AdamW
  params:
    lr: 1e-4
    eps: 1e-6
    weight_decay: 1e-2


scheduler:
  name: cos
  min_learning_rate: 1e-6


grad_clip_params:
  max_norm: 1.0
  norm_type: inf
