defaults:
  - dataset: inria
  - augmentations: hard
  - loss: focal
  - model: seg_repvgg_unet
  - optimizer: adamw
  - runner: default
  - torch: default

batch_size: 4
channels_last: False
num_samples: 32
num_workers: 4

# DDP Stuff
local_rank: ${oc.env:LOCAL_RANK, 0}
world_size: ${oc.env:WORLD_SIZE, 0}

# Name of the experiment
experiment: null
seed: 42

transfer: null
checkpoint: null

# Hydra stuff
hydra:
  output_subdir: null # Disable saving of config files. We'll do that ourselves.
  run:
    dir: . # Set working dir to current directory
  sweep:
    dir: .
    subdir: .
