build: off

cache:
  - '%LOCALAPPDATA%\pip\Cache'

environment:

  matrix:
    - PYTHON: 'C:\Python27-x64'
    - PYTHON: 'C:\Python35-x64'
    - PYTHON: 'C:\Python36-x64'
    - PYTHON: 'C:\Python37-x64'

install:
  - '%PYTHON%\python.exe -m pip install -U pip wheel setuptools'
  - '%PYTHON%\python.exe -m pip install .[tests]'
  - '%PYTHON%\python.exe -m pip install "pydocstyle<4.0.0" flake8 flake8-docstrings'

test_script:
  - '%PYTHON%\python.exe -m pytest'
  - '%PYTHON%\python.exe -m flake8'
