group: travis_latest
language: python
cache: pip
branches:
  only:
  - master
  - develop
  - gh-pages
notifications:
  email:
    on_success: never
matrix:
  include:
  - python: 3.6
  - python: 3.7
    dist: xenial
    sudo: true
install:
- if [[ "$TEST_MODE" == "DOCS" ]]; then pip install -q .; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then pip install -q .[tests]; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then pip install "pydocstyle<4.0.0" flake8 flake8-docstrings; fi
script:
- if [[ "$TEST_MODE" != "DOCS" ]]; then pytest; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then flake8; fi
deploy:
  provider: pypi
  user: BloodAxe
  password:
    secure: Xmwz0QnikjxZ9PNKbxGo6KZHJZVXLtrjciVwNv7p/iAFQ35ORZ6Kd5aW6Ktqyr9s2s48N9zNJizJfLYtiK8hW9YM9LQLt1HTToLaeXyaAPoBOAdVYTO9iNGq9Vg4DP9fDBYtfW4dfcD/jbZ370bzJTBv2J90hjwJG1Ev2FPMfVLjxN380Gu1Q3WJxFDS4HLL2vzUrb+Rv37oUksZwkxMPWeXpEvUmm9KtNw1W3kLrISaUy10iAVsonCf3nKrE/A9YuIQ5u2aaNE+Mv6OPcsENYFJcORcM4jIH6XlRce0Z/OMs16YjyqLk43gVrymXK3nbIcVnwOu0VlDbyvgwOcQ9S7BG1rn2sx4+fuGv5ETSeMx9XX6YzKFrrff3NDG9g/k373upF+t1O2HEwzYZWGibjnUgLWU7dp+9y8tnIznyd7wsaxNXxy1gUArcQE6TDHCV922as70+GkxpjfFACx/E4HnhWgnWCl3B6lSyCKcB1Fha00rCADqV2m/XZIRQMiwa1ueuxDQQYHCXABVLnppv1K7CbRnIQq9f7yt6Yzadqc/7id277/ayCj/9KVcXPycFmauPUAVti+p/z/HwkmhMVy7OX4k+nn04jLzOUW3ZVweeKk6jS/jSJbyctURUeLdUHGEpxxngfqUu5BNmYvAptbKCouUns8TiiT0zhVfZSk=
