language: python

notifications:
  email:
    on_success: never

cache:
  directories:
    - $HOME/.cache/pip

matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
      sudo: true

install:
- if [[ "$TEST_MODE" == "DOCS" ]]; then pip install -q .; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then pip install -q .[tests]; fi
- if [[ "$TEST_MODE" != "DOCS" ]]; then pip install flake8 flake8-docstrings; fi

script:
  - if [[ "$TEST_MODE" != "DOCS" ]]; then pytest; fi
  - if [[ "$TEST_MODE" != "DOCS" ]]; then flake8; fi
