aggregation: sum
losses:
  - loss:
      _target_: torch.nn.BCEWithLogitsLoss
    prefix: loss/bce
    target_key: TARGET_MASK_KEY
    output_key: OUTPUT_MASK_KEY
    weight: 1.0

  - loss:
      _target_: pytorch_toolbelt.losses.DiceLoss
      mode: binary
      from_logits: True
      log_loss: True
    prefix: loss/dice
    target_key: TARGET_MASK_KEY
    output_key: OUTPUT_MASK_KEY
    weight: 0.1
