aggregation: sum
losses:
  - loss:
      _target_: pytorch_toolbelt.losses.BinaryFocalLoss
    prefix: loss/focal
    target_key: TARGET_MASK_KEY
    output_key: OUTPUT_MASK_KEY
    weight: 10.0

  - loss:
      _target_: pytorch_toolbelt.losses.JaccardLoss
      mode: binary
      from_logits: True
      log_loss: True
    prefix: loss/jaccard
    target_key: TARGET_MASK_KEY
    output_key: OUTPUT_MASK_KEY
    weight: 0.1
