input_key: INPUT_IMAGE_KEY
output_key:

architecture:
  _target_: painless_sota.inria_aerial.models.PercieverIOForSegmentation
  config:
    _target_: painless_sota.inria_aerial.models.PerceiverConfig

    preprocessor:
      _target_: painless_sota.inria_aerial.models.Space2DepthPreprocessorConfig
      num_input_channels: 3
      spatial_shape: ${dataset.train.dataset.image_size}
      factor: 4
      with_bn: True
      activation: gelu
      kernel_size: 3
      num_output_channels: 64

    position_encoding:
      _target_: painless_sota.inria_aerial.models.FourierPositionEncodingConfig
      num_frequency_bands: 64
      include_positions: True
      num_output_channels:

    encoder:
      _target_: painless_sota.inria_aerial.models.EncoderConfig

      num_latent_channels: 512
      num_latents: 2048

      num_cross_attention_heads: 1
      num_cross_attention_layers: 1
      num_cross_attention_qk_channels: 512

      num_self_attention_heads: 8
      num_self_attention_layers_per_block: 16
      num_self_attention_blocks: 1

      dropout: 0.05
      init_scale: 0.02

      attention_residual: True
      activation: gelu
      activation_checkpointing: True

    decoder:
      _target_: painless_sota.inria_aerial.models.DecoderConfig

      init_scale: 0.02
      num_cross_attention_heads: 1
      dropout: 0.05

      activation: gelu
      attention_residual: False
      activation_checkpointing: True

    output_query:
      _target_: painless_sota.inria_aerial.models.FourierPositionEncodingQueryConfig

    postprocessor:
      _target_: painless_sota.inria_aerial.models.Depth2SpacePostprocessorConfig
      num_output_channels: ${dataset.num_output_classes}
      factor: ${model.architecture.config.preprocessor.factor}
      output_name: OUTPUT_MASK_KEY
      activation: gelu
