input_key: INPUT_IMAGE_KEY
output_key:

architecture:
  _target_: painless_sota.inria_aerial.models.SegmentationUNet.from_config
  _recursive_: False
  config:
    activation: relu
    num_channels: ${dataset.num_input_channels}

    encoder:
      _target_: pytorch_toolbelt.modules.encoders.TimmResnet200D
      drop_path_rate: 0.2
      pretrained: True
      layers:
        - 0 # 2
        - 1 # 4
        - 2 # 8
        - 3 # 16
        - 4 # 32

    decoder:
      upsample_type: rdtsc
      block_type: IRBlock
      channels:
        - 64
        - 128
        - 256
        - 512

    segmentation:
      _target_: painless_sota.inria_aerial.models.PixelShufflePredictionsHead
      channels: ${model.architecture.config.decoder.channels}
      num_classes: ${dataset.num_output_classes}
      scale_factor: 2
      dropout_rate: 0.1
      output_name: OUTPUT_MASK_KEY
