input_key: INPUT_IMAGE_KEY
output_key:

architecture:
  _target_: painless_sota.inria_aerial.models.RepVGGUnet.from_config
  config:
    num_channels: ${dataset.num_input_channels}
    activation: silu
    encoder: RepVGG-B2
    decoder_features: [128, 256, 384, 512]
    drop_path_rate: 0.1

    segmentation:
      _target_: painless_sota.inria_aerial.models.PixelShufflePredictionsHead
      channels: ${model.architecture.config.decoder_features}
      num_classes: ${dataset.num_output_classes}
      output_name: OUTPUT_MASK_KEY