input_key: INPUT_IMAGE_KEY
output_key:

architecture:
  _target_: painless_sota.inria_aerial.models.SegmentationUNet.from_config
  config:
    slug: seg_r200d_unet
    activation: relu
    num_channels: ${dataset.num_input_channels}

    encoder:
      _target_: pytorch_toolbelt.modules.encoders.TimmResnet200D
      pretrained: True
      layers:
        - 1 # 4
        - 2 # 8
        - 3 # 16
        - 4 # 32

    decoder:
      upsample_type: bilinear
      block_type: IRBlock
      channels:
        - 256
        - 384
        - 512

    segmentation:
      _target_: painless_sota.inria_aerial.models.SimpleSegmentationHead
      channels: ${model.architecture.config.decoder.channels}
      num_classes: ${dataset.num_output_classes}
      dropout_rate: 0.1
      output_name: OUTPUT_MASK_KEY