name: CI
on: [push, pull_request]

jobs:
  test_and_lint:
    name: Test and lint
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        pytorch-toolbelt-version: [tests]
      fail-fast: false
    steps:
    - name: Checkout
      uses: actions/checkout
    - name: Set up Python
      uses: actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install PyTorch on Linux and Windows
      if: >
        matrix.operating-system == 'ubuntu-latest' ||
        matrix.operating-system == 'windows-latest'
      run: >
        pip install torch==1.10.1+cpu torchvision==0.11.2+cpu
        -f https://download.pytorch.org/whl/torch_stable.html
    - name: Install PyTorch on MacOS
      if: matrix.operating-system == 'macos-latest'
      run: pip install torch==1.10.1 torchvision==0.11.2
    - name: Install dependencies
      run: pip install .[${{ matrix.pytorch-toolbelt-version }}]
    - name: Install linters
      run: pip install flake8==5
    - name: Run PyTest
      run: pytest
    - name: Run Flake8
      run: flake8
#    - name: Install MyPy
#      run: pip install mypy==0.800
#    - name: Run mypy
#      run: mypy .

  check_code_formatting:
    name: Check code formatting with Black
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - name: Checkout
      uses: actions/checkout
    - name: Set up Python
      uses: actions/setup-python
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update pip
      run: python -m pip install --upgrade pip
    - name: Install Black
      run: pip install black==22.10.0
    - name: Run Black
      run: black --config=black.toml --check .
